### ISSUE TITLE
Improve Readme 

### ISSUE THREAD

**Issue by ratnakar5938** [ratnakar5938/Whatsapp-clone#3]
Project logo- 
[Logo](https://res.cloudinary.com/ratnakar5938/image/upload/v1635397981/Whatsapp%20clone/wp_pvgx7o.png)

Screenshots - 
[chats](https://res.cloudinary.com/ratnakar5938/image/upload/v1635397324/Whatsapp%20clone/Screenshot_125_f8wwhf.png)
[Login](https://res.cloudinary.com/ratnakar5938/image/upload/v1635397305/Whatsapp%20clone/Screenshot_124_ttmgmz.png)

package installer-
yarn

**Comment by panvalkar1994** [comment]
Hi @ratnakar5938 , I think this issue is complete. Can you specify why it is open, so i can help.

**Comment by ratnakar5938** [comment]
@panvalkar1994 sorry actually I forgot to close this issue

**Comment by panvalkar1994** [comment]
No Problem.
